### ISSUE TITLE
can't seem to get this to work for this season.

### ISSUE THREAD

**Issue by jclrk279** [JakeKandell/NBA-Predict#11]
Predictions for 01/06/2021:
Traceback (most recent call last):
  File "c:\Users\Documents\Python\NBA-Predict\nbaPredict.py", line 95, in <module>
    makeInterpretPredictions('01/06/2021', '2020-21', '12/11/2020')
  File "c:\Users\Documents\Python\NBA-Predict\nbaPredict.py", line 89, in makeInterpretPredictions       
    predictions = predictDailyGames(currentDate, season, startOfSeason)
  File "c:\Users\Documents\Python\NBA-Predict\nbaPredict.py", line 55, in predictDailyGames
    pickleModel = pickle.load(file)
ModuleNotFoundError: No module named 'sklearn.linear_model.logistic'

**Comment by nbognar5** [comment]
I am having the same issue... let me know if you find a fix

**Comment by JakeKandell** [comment]
Sorry for the late response, I mentioned this to someone else but f I had to guess, this issue stems from you having a newer version of Scikit-learn. The logistic regression model was deprecated in newer versions of Scikit-learn, so you need to make sure that the specific version of Scikit-learn that is installed is 21.2.

**Comment by nbognar5** [comment]
> Sorry for the late response, I mentioned this to someone else but f I had to guess, this issue stems from you having a newer version of Scikit-learn. The logistic regression model was deprecated in newer versions of Scikit-learn, so you need to make sure that the specific version of Scikit-learn that is installed is 21.2.

Yes, I also came to that conclusion. I am trying to download version 0.21.2 via python 2.7.9, but still cannot get version 21.2 to download.

**Comment by JakeKandell** [comment]
I'm not sure, but you may need Python 3. That's what I used personally.
