### ISSUE TITLE
 HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=600)

### ISSUE THREAD

**Issue by crmsci** [JakeKandell/NBA-Predict#14]
![NBA.jpg](https://i.loli.net/2021/04/19/vXeErVIcS1ULfMx.jpg)

Hello, I downloaded and run the prompt from the warehouse, I searched a lot of answers from the Internet, but still did not find a solution. Can you give me a solution? Thanks a lot

https://github.com/swar/nba_api/issues/176
https://github.com/swar/nba_api/issues/94

**Comment by JakeKandell** [comment]
You can trying searching through the code for the time.sleep() functions and increasing the time in there. For example, change time.sleep(1) to time.sleep(3). It's likely just an issue with making too many requests in a certain time period, but I don't have any control over it other than those time.sleep() functions.
