### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by fabiomig** [JakeKandell/NBA-Predict#2]
Hi @JakeKandell 

First of all thanks for open source your work.

Im trying to run it on my mac but no luck so far.

What OS are you using?

Can you make a guide how to run it?

Thanks in advance!

Fábio

**Comment by JakeKandell** [comment]
I've tried it on MacOS, Windows, and Linux and it has worked on all of them. Did you look at the README which gives some basic instructions on how to run the model? If so, what part are you having trouble with so I can try and help you out?

**Comment by fabiomig** [comment]
Fabios-MacBook-Pro:NBA-Predict fabio$ python nbaPredict.py
Traceback (most recent call last):
  File "nbaPredict.py", line 7, in <module>
    from getDailyMatchups import dailyMatchupsPresent
  File "/Users/fabio/Projetos/NBA-Predict/getDailyMatchups.py", line 3, in <module>
    from nba_api.stats.endpoints import leaguegamelog, scoreboard
ImportError: No module named nba_api.stats.endpoints

**Comment by JakeKandell** [comment]
So your problem is that you don't have the modules installed that are necessary. [Here's a link that tells you how to install modules because it's pretty easy.] (https://docs.python.org/3/installing/index.html) The modules that you will need to install for this program to run are as follows: pandas, nba_api, and scikit-learn(version 21.2). After installing these, you should be able to run the program. Let me know if you have any further issues.

**Comment by fabiomig** [comment]
It's working now hehehe. Thanks.

Another question. 
What model is used when you call nbaPredictions ? 
Is created on the fly or is a model that is prefected over the time?

I mean, i see a file called createModel. Do i need to create an model before calling the predictions to have better accuracy for the current season?

Thanks in advance

**Comment by JakeKandell** [comment]
The model that is used is the finalized_model located in the SavedModels folder. This model was generated in the past using data from past games in the 2018-19 season. The createModel folder was what was used to create the model and can be used to generate new models if you want. You don't need to create a new model before calling the predictions.
