### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by itzvenom** [JakeKandell/NBA-Predict#3]
Hello, first of all thank you for your work, a masterpiece.

Can you help me troubleshoot and solve this.

> C:\Users\sergi\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.linear_model.logistic module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.linear_model. Anything that cannot be imported from sklearn.linear_model is now part of the private API.
  warnings.warn(message, FutureWarning)
C:\Users\sergi\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\base.py:313: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.21.2 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(

>

**Comment by JakeKandell** [comment]
Firstly, this error shouldn't cause the program to break and will still allow it to run perfectly. However, the reason for the error is that you installed the wrong version of scikit-learn. To resolve this, you should uninstall scikit-learn version 0.22 and install version 0.21.2. Let me know if you have any more questions.

**Comment by itzvenom** [comment]
Hello @JakeKandell first of all sorry for reopening the issue, although lately I haven't been managed to run the script because of this:

> Traceback (most recent call last):
>   File "C:\Users\sergi\.virtualenvs\NBA-master-iNU-nypu\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 3, in raise_from
>   File "C:\Users\sergi\.virtualenvs\NBA-master-iNU-nypu\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
>     httplib_response = conn.getresponse()
>   File "C:\Users\sergi\Anaconda3\Lib\http\client.py", line 1336, in getresponse
>     response.begin()
>   File "C:\Users\sergi\Anaconda3\Lib\http\client.py", line 306, in begin
>     version, status, reason = self._read_status()
>   File "C:\Users\sergi\Anaconda3\Lib\http\client.py", line 267, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "C:\Users\sergi\Anaconda3\Lib\socket.py", line 589, in readinto
>     return self._sock.recv_into(b)
>   File "C:\Users\sergi\Anaconda3\Lib\ssl.py", line 1071, in recv_into
>     return self.read(nbytes, buffer)
>   File "C:\Users\sergi\Anaconda3\Lib\ssl.py", line 929, in read
>     return self._sslobj.read(len, buffer)
> socket.timeout: The read operation timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\sergi\.virtualenvs\NBA-master-iNU-nypu\lib\site-packages\requests\adapters.py", line 449, in send
>     timeout=timeout
>   File "C:\Users\sergi\.virtualenvs\NBA-master-iNU-nypu\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
>     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
>   File "C:\Users\sergi\.virtualenvs\NBA-master-iNU-nypu\lib\site-packages\urllib3\util\retry.py", line 400, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "C:\Users\sergi\.virtualenvs\NBA-master-iNU-nypu\lib\site-packages\urllib3\packages\six.py", line 735, in reraise
>     raise value
>   File "C:\Users\sergi\.virtualenvs\NBA-master-iNU-nypu\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
>     chunked=chunked,
>   File "C:\Users\sergi\.virtualenvs\NBA-master-iNU-nypu\lib\site-packages\urllib3\connectionpool.py", line 423, in _make_request
>     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
>   File "C:\Users\sergi\.virtualenvs\NBA-master-iNU-nypu\lib\site-packages\urllib3\connectionpool.py", line 331, in _raise_timeout
>     self, url, "Read timed out. (read timeout=%s)" % timeout_value
> urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\sergi\Desktop\NBA-master\predictions\predictions.py", line 41, in __init__
>     self.inputs = self.generate_inputs()
>   File "C:\Users\sergi\Desktop\NBA-master\predictions\predictions.py", line 44, in generate_inputs
>     home_games = leaguegamefinder.LeagueGameFinder(team_id_nullable=self.HOME_TEAM_ID).get_data_frames()[0]
>   File "C:\Users\sergi\.virtualenvs\NBA-master-iNU-nypu\lib\site-packages\nba_api\stats\endpoints\leaguegamefinder.py", line 204, in __init__
>     self.get_request()
>   File "C:\Users\sergi\.virtualenvs\NBA-master-iNU-nypu\lib\site-packages\nba_api\stats\endpoints\leaguegamefinder.py", line 212, in get_request
>     timeout=self.timeout,
>   File "C:\Users\sergi\.virtualenvs\NBA-master-iNU-nypu\lib\site-packages\nba_api\library\http.py", line 123, in send_api_request
>     response = requests.get(url=base_url, params=parameters, headers=request_headers, proxies=proxies, timeout=timeout)
>   File "C:\Users\sergi\.virtualenvs\NBA-master-iNU-nypu\lib\site-packages\requests\api.py", line 75, in get
>     return request('get', url, params=params, **kwargs)
>   File "C:\Users\sergi\.virtualenvs\NBA-master-iNU-nypu\lib\site-packages\requests\api.py", line 60, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "C:\Users\sergi\.virtualenvs\NBA-master-iNU-nypu\lib\site-packages\requests\sessions.py", line 533, in request
>     resp = self.send(prep, **send_kwargs)
>   File "C:\Users\sergi\.virtualenvs\NBA-master-iNU-nypu\lib\site-packages\requests\sessions.py", line 646, in send
>     r = adapter.send(request, **kwargs)
>   File "C:\Users\sergi\.virtualenvs\NBA-master-iNU-nypu\lib\site-packages\requests\adapters.py", line 529, in send
>     raise ReadTimeout(e, request=request)
> requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)

Do you know how to fix it?

**Comment by JakeKandell** [comment]
This issue is occurring because it appears that something has changed with the stats.nba.com api that I used for this project. There is an issue thread over on the page for nba_api where many people seem to be having the same problem as you. The creator of the api mentioned that he will work on fixing the issues this weekend, so if it's able to fixed I will let you know.

**Comment by JakeKandell** [comment]
The issue should be fixed now. You just should redownload the updated headers file and download the updated version of nba-api.

**Comment by itzvenom** [comment]
> The issue should be fixed now. You just should redownload the updated headers file and download the updated version of nba-api.

Confimed! Working again!
