### ISSUE TITLE
Unable to get makePastPredictions.py to work to predict all the games of the 2010-11 season

### ISSUE THREAD

**Issue by RaghavKirpekar** [JakeKandell/NBA-Predict#6]
Hi, I wanted to use this python file to basically generate a csv file with the game info for the whole 2010-11 season but as soon as I run this file like the readme instructed, I run into an error. Any help is welcome. Thanks!

P.S. : This is a very amazing project!

**Comment by JakeKandell** [comment]
Thanks you very much! I have two questions.

1. Have you successfully generate a csv file for other seasons or is 2010-2011 the only season you tried?

2. Can you send a screenshot of the error you are getting and another of what you are entering into the program to scrape the 2010-2011 season?

**Comment by RaghavKirpekar** [comment]
Answer 1: No, I tried it only for the 2010-11 season to start with and was unable to successfully generate a csv file.

Answer 2: 
![image](https://user-images.githubusercontent.com/31844372/78197742-e2b18f00-74a3-11ea-8950-451d39203ab9.png)

![image](https://user-images.githubusercontent.com/31844372/78197799-0d9be300-74a4-11ea-9edb-c023fd0a8c56.png)

**Comment by RaghavKirpekar** [comment]
Maybe what I entered as the parameters was wrong?

**Comment by RaghavKirpekar** [comment]
Answer 1: No this was the first one I tried and was not able to successfully generate a csv file.

Answer 2: 
![image](https://user-images.githubusercontent.com/31844372/78197986-ba766000-74a4-11ea-839e-3dddada9f167.png)

![image](https://user-images.githubusercontent.com/31844372/78198024-e396f080-74a4-11ea-88df-a9d7707c6631.png)

Maybe what I entered as parameters was wrong?

**Comment by JakeKandell** [comment]
Hmm, the parameters don't look wrong. Can you try changing that 26 to 27 and let me know if that still doesn't work? If not, I'll take a look myself.

**Comment by RaghavKirpekar** [comment]
Nope, still gives an error. But a different one this time. Something to do with the startDate and endDate variables being passed but not able to figure it out myself.

![image](https://user-images.githubusercontent.com/31844372/78298792-a38d4780-7550-11ea-8ac2-d8d2dd737dca.png)

The returned list from the endpoint is coming up empty cause of the dates I think.

**Comment by JakeKandell** [comment]
Weird, I'll take a look tomorrow and let you know if I can figure out what's wrong.

**Comment by JakeKandell** [comment]
Sorry for the delay but I think I found the issue. The issue was that you were trying to have the model predict the first games that some teams had played in the season. In doing this, there were no previous stats for the model to base its predictions off of which led to errors. I've added a note in the comments that states that you should only start the predictions at least three days after the season starts. 

In investigating your issue, I also noticed that there was a bug for teams whose names have changed over the years like the New Jersey Nets. Hopefully, this should now be fixed with my latest update to the repo. Let me know if you have any other issues.

**Comment by RaghavKirpekar** [comment]
Wow! It's working great now!
Just had to make one addition, nothing major but I just had to add "Los Angeles Clippers" to the teamID python file(only because that is their name for the 2010-11 season for some reason smh)
Then it's working perfectly!
Thanks a lot!
Keep up the great work dude. :)

**Comment by JakeKandell** [comment]
Awesome! Thanks for letting me know about the Clippers too, I'll make sure to add that in.
