### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by guwoop** [JakeKandell/NBA-Predict#8]
Hi Jake, wondering if this require any updates. I tired running it but getting the following error.

Predictions for 12/23/2020:
Traceback (most recent call last):
  File "nbaPredict.py", line 95, in <module>
    makeInterpretPredictions('12/23/2020', '2020-21', '12/22/2020')
  File "nbaPredict.py", line 89, in makeInterpretPredictions
    predictions = predictDailyGames(currentDate, season, startOfSeason)
  File "nbaPredict.py", line 44, in predictDailyGames
    dailyGamesList = dailyGamesDataFrame(dailyGames, meanDict, standardDeviationDict, startOfSeason, currentDate, season)
  File "nbaPredict.py", line 22, in dailyGamesDataFrame
    homeTeamStats = getStatsForTeam(homeTeam, startDate, endDate, season)
  File "/Users/VV/Desktop/NBA-Predict-master/getStats.py", line 17, in getStatsForTeam
    generalTeamDashboard = generalTeamDict['OverallTeamDashboard'][0]
IndexError: list index out of range

Thanks.

**Comment by JakeKandell** [comment]
Because of the way the model works, it's unable to predict games until at least 4 days into the season. Let me know if this problem is still happening,  but I think it should be fine now since the season started 6 days ago.

**Comment by guwoop** [comment]
I tried running it again but currently stuck with this everytime.

NBA-Predict-master % python3 nbaPredict.py
Predictions for 12/29/2020:
Traceback (most recent call last):
  File "nbaPredict.py", line 95, in <module>
    makeInterpretPredictions('12/29/2020', '2020-21', '12/22/2020')
  File "nbaPredict.py", line 89, in makeInterpretPredictions
    predictions = predictDailyGames(currentDate, season, startOfSeason)
  File "nbaPredict.py", line 55, in predictDailyGames
    pickleModel = pickle.load(file)
ModuleNotFoundError: No module named 'sklearn.linear_model.logistic'

I had ran pip3 install requirements.txt to make sure I have everything installed in order to run it but can't seem to figure out what is causing this.

Thanks again

**Comment by JakeKandell** [comment]
I'm not sure but if I had to guess, this issue stems from you having a newer version of Scikit-learn. The logistic regression model was deprecated in newer versions of Scikit-learn, so you need to make sure that the version of Scikit-learn that is installed is 21.2.
